# Generated by Django 5.1.1 on 2024-09-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_alter_attendance_punch_in_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out',
            field=models.DateTimeField(null=True),
        ),
    ]
