# Generated by Django 5.1.1 on 2024-09-30 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_alter_attendance_punch_in_alter_attendance_punch_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
