# Generated by Django 5.1.1 on 2024-09-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_alter_attendance_punch_in_alter_attendance_punch_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(),
        ),
    ]
